package report

const htmlTemplate = `<!doctype html>
<html lang="{{.Locale}}" dir="{{if .RTL}}rtl{{else}}ltr{{end}}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>VPS Scope · {{.Report.Host.Hostname}}</title><style>
:root{color-scheme:dark;--bg:#090d18;--panel:#111827;--panel2:#0c1322;--line:#263249;--text:#eef2f8;--muted:#9aa7bb;--risk:#ff6675;--pass:#45d483;--info:#63a9ff;--unknown:#f2ba57;--shadow:0 16px 40px rgba(0,0,0,.22);font:15px/1.55 Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif}
*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 15% 0,#16213a 0,transparent 34rem),var(--bg);color:var(--text)}main{max-width:1160px;margin:auto;padding:38px 28px 72px}.hero{display:flex;justify-content:space-between;align-items:flex-start;gap:28px}.eyebrow{color:var(--info);font-size:.76rem;font-weight:800;letter-spacing:.16em;text-transform:uppercase}h1{font-size:clamp(2rem,5vw,3.3rem);line-height:1.05;margin:.35rem 0 .6rem;letter-spacing:-.045em}.subtitle,.muted{color:var(--muted)}.readonly{border:1px solid #365072;background:#111d31;color:#b9d8ff;border-radius:999px;padding:7px 12px;font-size:.8rem;white-space:nowrap}.host-grid,.summary{display:grid;gap:12px}.host-grid{grid-template-columns:repeat(4,1fr);margin:26px 0}.host-item,.card,.finding,.toolbar{background:color-mix(in srgb,var(--panel) 94%,transparent);border:1px solid var(--line);box-shadow:var(--shadow)}.host-item{border-radius:12px;padding:12px 14px}.host-item span{display:block;color:var(--muted);font-size:.76rem;text-transform:uppercase;letter-spacing:.06em}.host-item strong{display:block;margin-top:3px;overflow-wrap:anywhere}.summary{grid-template-columns:repeat(4,1fr);margin:14px 0 20px}.card{border-radius:15px;padding:17px 18px;border-top:3px solid var(--accent)}.card .label{font-size:.78rem;font-weight:800;letter-spacing:.12em;color:var(--accent)}.number{font-size:2.25rem;line-height:1.15;font-weight:760;margin-top:4px}.risk{--accent:var(--risk)}.pass{--accent:var(--pass)}.info{--accent:var(--info)}.unknown{--accent:var(--unknown)}
.assessment{display:grid;gap:9px}.assessment-line{display:grid;grid-template-columns:9rem 7rem 1fr;gap:12px;align-items:start;background:var(--panel2);border:1px solid var(--line);border-radius:10px;padding:11px 12px}.assessment-status{font-size:.76rem;font-weight:850;letter-spacing:.04em}.assessment-line[data-status^="RISK"] .assessment-status{color:var(--risk)}.assessment-line[data-status^="PASS"] .assessment-status{color:var(--pass)}.assessment-line[data-status^="UNKNOWN"] .assessment-status{color:var(--unknown)}.assessment-line[data-status^="INFO"] .assessment-status{color:var(--info)}
.toolbar{position:sticky;top:10px;z-index:3;display:flex;gap:10px;align-items:center;flex-wrap:wrap;border-radius:14px;padding:10px;margin:22px 0;background:rgba(12,19,34,.9);backdrop-filter:blur(14px)}.filters{display:flex;gap:6px;flex-wrap:wrap}.filter{appearance:none;border:1px solid var(--line);background:#172036;color:var(--muted);border-radius:9px;padding:7px 10px;cursor:pointer;font:inherit;font-size:.82rem}.filter:hover,.filter[aria-pressed="true"]{color:var(--text);border-color:#526582;background:#22304a}.search{min-width:220px;flex:1;border:1px solid var(--line);background:#080d18;color:var(--text);border-radius:9px;padding:8px 11px;font:inherit}.search::placeholder{color:#71809a}
.action-link{color:inherit;text-decoration-color:color-mix(in srgb,var(--info) 62%,transparent);text-decoration-thickness:.09em;text-underline-offset:.16em}.action-link:hover,.action-link:focus-visible{color:var(--info);text-decoration-color:currentColor}.action-link:focus-visible{outline:2px solid var(--info);outline-offset:3px;border-radius:3px}.action-id{direction:ltr;unicode-bidi:embed;white-space:nowrap}.findings{display:grid;gap:13px}.finding{--accent:var(--info);border-radius:14px;padding:0;border-inline-start:4px solid var(--accent);overflow:hidden;scroll-margin-top:6.5rem}.finding[data-status="RISK"]{--accent:var(--risk)}.finding[data-status="PASS"]{--accent:var(--pass)}.finding[data-status="UNKNOWN"]{--accent:var(--unknown)}.finding[data-na="true"]{opacity:.68}.finding-head{display:grid;grid-template-columns:auto 1fr auto;gap:13px;align-items:start;padding:16px 18px}.pill{color:var(--accent);background:color-mix(in srgb,var(--accent) 12%,transparent);border:1px solid color-mix(in srgb,var(--accent) 35%,transparent);border-radius:8px;padding:4px 7px;font-size:.7rem;font-weight:850;letter-spacing:.06em}.finding h2{font-size:1.08rem;line-height:1.35;margin:0}.finding-meta{color:var(--muted);font-size:.78rem;margin-top:4px;direction:ltr;unicode-bidi:embed}.severity{color:var(--risk);font-size:.76rem;font-weight:800;text-transform:uppercase}.finding-body{padding:0 18px 17px 18px}.explain{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:13px}.explain p{margin:0;background:var(--panel2);border-radius:9px;padding:11px 12px}.explain b{display:block;color:var(--muted);font-size:.73rem;text-transform:uppercase;letter-spacing:.06em;margin-bottom:4px}details{border-top:1px solid var(--line);margin-top:13px;padding-top:10px}summary{cursor:pointer;color:var(--muted);font-size:.82rem}.evidence-list{display:grid;gap:7px;margin-top:9px}.evidence{direction:ltr;text-align:left;font:12px/1.55 ui-monospace,SFMono-Regular,Consolas,monospace;background:#080d18;border:1px solid #1e2a3d;padding:9px 10px;border-radius:8px;overflow-wrap:anywhere}.source{color:#85b9ff}.error{color:var(--unknown);background:#2a2112;border-radius:8px;padding:10px 12px}.empty{display:none;text-align:center;color:var(--muted);padding:50px 10px}.footer{color:var(--muted);font-size:.8rem;margin-top:30px;text-align:center}
@media(prefers-color-scheme:light){:root{color-scheme:light;--bg:#f4f7fb;--panel:#fff;--panel2:#f5f7fb;--line:#d8e0eb;--text:#172033;--muted:#617087;--shadow:0 12px 32px rgba(44,62,86,.09)}body{background:radial-gradient(circle at 15% 0,#e4edff 0,transparent 34rem),var(--bg)}.toolbar{background:rgba(255,255,255,.9)}.filter{background:#f5f7fb}.filter:hover,.filter[aria-pressed="true"]{background:#e9eff8}.search,.evidence{background:#f7f9fc}.readonly{background:#eaf2ff;color:#285585}}
@media(max-width:760px){main{padding:24px 14px 50px}.hero{display:block}.readonly{display:inline-block;margin-top:12px}.host-grid,.summary{grid-template-columns:repeat(2,1fr)}.assessment-line{grid-template-columns:1fr auto}.assessment-line span:last-child{grid-column:1/-1}.finding-head{grid-template-columns:auto 1fr}.severity{grid-column:2}.explain{grid-template-columns:1fr}.toolbar{top:5px}.search{width:100%;min-width:0}}
@media print{body{background:#fff}.toolbar{display:none}main{max-width:none;padding:0}.action-link{color:inherit;text-decoration:none}.finding{scroll-margin-top:0}.finding,.card,.host-item{box-shadow:none;break-inside:avoid}details:not([open])>*:not(summary){display:block}.footer{margin-top:15px}}
</style></head><body><main>
<header class="hero"><div><div class="eyebrow">{{t "代理 VPS 安全审计" "Proxy VPS security audit"}}</div><h1>VPS Scope</h1><div class="subtitle">{{t "自建代理、隧道和隐私网络 VPS 的安全与运行状态报告" "Security and runtime report for self-hosted proxy, tunnel, and privacy-network VPS hosts"}}</div></div></header>
<section class="host-grid" aria-label="{{t "主机信息" "Host context"}}"><div class="host-item"><span>{{t "主机" "Host"}}</span><strong>{{.Report.Host.Hostname}}</strong></div><div class="host-item"><span>{{t "系统" "System"}}</span><strong>{{.Report.Host.OS}} {{.Report.Host.OSVersion}}</strong></div><div class="host-item"><span>Profile</span><strong>{{.Report.Profile.Effective}}</strong></div><div class="host-item"><span>{{t "完成时间" "Finished"}}</span><strong>{{.Report.FinishedAt.Format "2006-01-02 15:04 UTC"}}</strong></div></section>
<section class="summary" aria-label="{{t "摘要" "Summary"}}"><div class="card risk"><div class="label">RISK</div><div class="number">{{.Report.Summary.Risk}}</div></div><div class="card pass"><div class="label">PASS</div><div class="number">{{.Report.Summary.Pass}}</div></div><div class="card info"><div class="label">INFO</div><div class="number">{{.Report.Summary.Info}}</div></div><div class="card unknown"><div class="label">UNKNOWN</div><div class="number">{{.Report.Summary.Unknown}}</div></div></section>
{{if .TimedOut}}<section class="card unknown"><h2>UNKNOWN</h2><p>{{t "审计已达到截止时间。本报告保留了已完成的证据；未运行的检查标记为 UNKNOWN。" "Audit deadline reached. This report preserves completed evidence; checks that did not run are UNKNOWN."}}</p></section>{{end}}
{{if .Assessment.HasContent}}<section class="card"><h2>{{t "代理 VPS 结论" "Proxy VPS assessment"}}</h2>{{if .Assessment.Components}}<p><b>{{t "识别到" "Detected"}}:</b> {{range $index, $component := .Assessment.Components}}{{if $index}}, {{end}}{{$component}}{{end}}</p>{{end}}<div class="assessment">{{range .Assessment.Lines}}<div class="assessment-line" data-status="{{.Status}}"><strong>{{.Label}}</strong><span class="assessment-status">{{.Status}}</span><span>{{.Message}}</span></div>{{end}}</div></section>{{end}}
<section class="card"><h2>{{.Verdict.Headline}}</h2><p>{{.Verdict.Detail}}</p><p class="muted">PASS = {{t "证据支持当前判断" "evidence supports the current judgment"}} · INFO = {{t "事实与上下文" "facts and context"}} · UNKNOWN = {{t "证据不足，不代表安全" "insufficient evidence, not safe by default"}}</p></section>
{{if or .Actions.Urgent .Actions.Availability .Actions.Maintenance .Actions.EvidenceGaps}}<section class="card"><h2>{{t "处理摘要" "Action summary"}}</h2>{{if .Actions.Urgent}}<h3>{{t "现在优先处理" "Handle now"}}</h3><ul>{{range .Actions.Urgent}}<li><a class="action-link" href="#{{anchor .Localized.ID}}"><strong>{{.Localized.Title}}</strong> <span class="action-id">({{.Localized.ID}})</span></a> — {{.Verdict}}</li>{{end}}</ul>{{end}}{{if .Actions.Availability}}<h3>{{t "可能影响可用性" "May affect availability"}}</h3><ul>{{range .Actions.Availability}}<li><a class="action-link" href="#{{anchor .Localized.ID}}"><strong>{{.Localized.Title}}</strong> <span class="action-id">({{.Localized.ID}})</span></a> — {{.Verdict}}</li>{{end}}</ul>{{end}}{{if .Actions.Maintenance}}<h3>{{t "例行维护与复核" "Maintenance and review"}}</h3><ul>{{range .Actions.Maintenance}}<li><a class="action-link" href="#{{anchor .Localized.ID}}"><strong>{{.Localized.Title}}</strong> <span class="action-id">({{.Localized.ID}})</span></a> — {{.Verdict}}</li>{{end}}</ul>{{end}}{{if .Actions.EvidenceGaps}}<h3>{{t "证据不足，需要人工确认" "Evidence gaps requiring confirmation"}}</h3><ul>{{range .Actions.EvidenceGaps}}<li><a class="action-link" href="#{{anchor .Localized.ID}}"><strong>{{.Localized.Title}}</strong> <span class="action-id">({{.Localized.ID}})</span></a> — {{.Verdict}}</li>{{end}}</ul>{{end}}</section>{{end}}
{{if .ProxyOverview.HasContent}}<section class="card"><h2>{{t "代理部署明细" "Proxy deployment details"}}</h2>{{if .ProxyOverview.Components}}<p><b>{{t "已识别组件" "Detected components"}}:</b> {{range $index, $component := .ProxyOverview.Components}}{{if $index}}, {{end}}{{$component}}{{end}}</p>{{end}}{{range .ProxyOverview.Groups}}<h3>{{.Title}}</h3><ul>{{range .Lines}}<li>{{.}}</li>{{end}}</ul>{{end}}</section>{{end}}
<section><h2>{{t "全部技术检查与证据" "All technical checks and evidence"}}</h2><p class="muted">{{t "以下是审计底稿；普通使用者通常只需阅读上面的结论和处理摘要。" "This is the audit record; most users only need the assessment and action summary above."}}</p></section>
<div class="toolbar"><div class="filters" role="group" aria-label="{{t "状态筛选" "Status filters"}}"><button class="filter" data-filter="ALL" aria-pressed="true">{{t "全部" "All"}}</button><button class="filter" data-filter="RISK" aria-pressed="false">RISK</button><button class="filter" data-filter="UNKNOWN" aria-pressed="false">UNKNOWN</button><button class="filter" data-filter="PASS" aria-pressed="false">PASS</button><button class="filter" data-filter="INFO" aria-pressed="false">INFO</button></div><input class="search" type="search" placeholder="{{t "搜索检查、证据或 ID" "Search checks, evidence, or IDs"}}" aria-label="{{t "搜索报告" "Search report"}}"></div>
<section class="findings" aria-label="{{t "检查结果" "Findings"}}">{{range .Findings}}<article class="finding" id="{{anchor .ID}}" data-status="{{.Status}}" data-na="{{.NotApplicable}}"><header class="finding-head"><div class="pill">{{.Status}}</div><div><h2>{{.Title}}</h2><div class="finding-meta">{{.ID}} · {{cat .Category}}{{if .ReasonCode}} · {{.ReasonCode}}{{end}}{{if .NotApplicable}} · {{t "不适用" "Not applicable"}}{{end}}</div></div>{{if .Severity}}<div class="severity">{{.Severity}}</div>{{end}}</header><div class="finding-body">{{if .Error}}<p class="error">{{.Error}}</p>{{end}}{{if or (eq .Status "RISK") (eq .Status "UNKNOWN")}}<div class="explain"><p><b>{{t "风险解释" "Why it matters"}}</b>{{.Why}}</p><p><b>{{t "建议" "Suggestion"}}</b>{{.Recommendation}}</p></div>{{end}}{{if .Evidence}}<details {{if or (eq .Status "RISK") (eq .Status "UNKNOWN")}}open{{end}}><summary>{{t "证据" "Evidence"}} · {{len .Evidence}}</summary><div class="evidence-list">{{range .Evidence}}<div class="evidence"><span class="source">[{{.Source}}]</span> {{evidence .}}</div>{{end}}</div></details>{{end}}</div></article>{{end}}</section>
<div class="empty">{{t "没有符合当前筛选条件的结果。" "No findings match the current filters."}}</div><footer class="footer">VPS Scope {{.Report.ToolVersion}} · schema {{.Report.SchemaVersion}} · {{t "报告保存在本地" "Report remains local"}}</footer>
</main><script>
(()=>{const buttons=[...document.querySelectorAll('[data-filter]')],items=[...document.querySelectorAll('.finding')],input=document.querySelector('.search'),empty=document.querySelector('.empty');let filter='ALL';const apply=()=>{const q=input.value.trim().toLowerCase();let shown=0;for(const item of items){const visible=(filter==='ALL'||item.dataset.status===filter)&&(!q||item.textContent.toLowerCase().includes(q));item.hidden=!visible;if(visible)shown++}empty.style.display=shown?'none':'block'};for(const button of buttons)button.addEventListener('click',()=>{filter=button.dataset.filter;for(const other of buttons)other.setAttribute('aria-pressed',String(other===button));apply()});input.addEventListener('input',apply)})();
</script></body></html>`
