package report

const htmlTemplate = `<!doctype html>
<html lang="{{.Locale}}" dir="{{if .RTL}}rtl{{else}}ltr{{end}}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>VPS Scope · {{.Report.Host.Hostname}}</title><style>
/* DOS Slate / CGA */
:root{color-scheme:dark;--report-theme:dos-slate-cga;--bg:#050605;--panel:#0b0c0a;--panel2:#080907;--line:#4e504a;--text:#c4c0b4;--bright:#ddd8c8;--muted:#77766f;--risk:#a95f55;--pass:#77966f;--info:#668b8c;--unknown:#a58a58;--font:"Courier New","Nimbus Mono PS","Liberation Mono","Noto Naskh Arabic","SimSun","Songti SC","宋体",serif;font:15px/1.55 var(--font)}
*{box-sizing:border-box;border-radius:0;box-shadow:none}html,body{background:var(--bg)}body{margin:0;color:var(--text);text-shadow:none;letter-spacing:0}body::before{content:"VPS SCOPE / TTY1 / AUDIT / 80x25";position:fixed;z-index:10;inset:0 0 auto;padding:3px 12px;color:#11120f;background:#aaa79c;font:12px/16px var(--font);direction:ltr;text-align:left;white-space:pre}main{max-width:920px;margin:0 auto;padding:38px 16px 44px}.hero{display:block;min-height:0;margin:0 0 12px;padding:14px 16px;border:1px solid var(--line);background:var(--panel)}.hero::before{content:"C:\\VPS-SCOPE> AUDIT /RUN\A[OK] SYS/FACTS\A[OK] NET/ENDPOINTS";display:block;white-space:pre-wrap;margin-bottom:11px;color:var(--muted);font-size:12px;line-height:1.5;direction:ltr;text-align:left}.hero h1{margin:2px 0 5px;color:var(--bright);font:700 28px/1.15 var(--font);letter-spacing:0}.eyebrow,.subtitle,.muted,.finding-meta{color:var(--muted);font-size:12px;letter-spacing:0}
.host-grid,.summary{display:grid;grid-template-columns:repeat(4,1fr);gap:0;margin:0 0 12px;border:1px solid var(--line);background:var(--panel)}.host-item{min-width:0;padding:9px 12px;border-inline-end:1px solid #363832}.host-item:last-child{border-inline-end:0}.host-item span{display:block;color:var(--muted);font-size:12px}.host-item span::before{content:"$ ";color:var(--pass)}.host-item strong{display:block;margin-top:5px;color:var(--bright);overflow-wrap:anywhere}.summary .card{min-height:69px;padding:9px 12px;border:0;border-inline-end:1px solid #363832;background:none}.summary .card:last-child{border-inline-end:0}.card .label{color:var(--accent);font:700 12px/1.1 var(--font);letter-spacing:0}.number{color:var(--accent);font:700 29px/1.1 var(--font);margin-top:4px}.risk{--accent:var(--risk)}.pass{--accent:var(--pass)}.info{--accent:var(--info)}.unknown{--accent:var(--unknown)}section.card{margin:0 0 12px;padding:12px;border:1px solid var(--line);background:var(--panel)}section.card>h2:first-child{margin-top:0;color:var(--bright);font-size:1.25rem}section.card h3{font-size:1rem}
.assessment{display:grid;gap:7px}.assessment-line{display:grid;grid-template-columns:9rem 7rem 1fr;gap:10px;align-items:start;padding:8px 9px;border:1px solid #363832;background:var(--panel2)}.assessment-status{font-size:12px;font-weight:700}.assessment-line[data-status^="RISK"] .assessment-status{color:var(--risk)}.assessment-line[data-status^="PASS"] .assessment-status{color:var(--pass)}.assessment-line[data-status^="UNKNOWN"] .assessment-status{color:var(--unknown)}.assessment-line[data-status^="INFO"] .assessment-status{color:var(--info)}
.toolbar{position:static;display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin:0 0 12px;padding:7px;border:1px solid var(--line);background:var(--panel);backdrop-filter:none}.filters{display:flex;gap:5px;flex-wrap:wrap}.filter,.search{height:29px;padding:4px 8px;border:1px solid var(--line);background:#070806;color:var(--text);font:12px/18px var(--font)}.filter{appearance:none;cursor:pointer}.filter::before{content:"["}.filter::after{content:"]"}.filter:hover,.filter[aria-pressed="true"]{color:#11120f;background:var(--text);border-color:var(--text)}.search{min-width:220px;flex:1}.search::placeholder{color:var(--muted)}
.action-link{color:inherit;text-decoration-color:var(--info);text-decoration-thickness:.09em;text-underline-offset:.16em}.action-link:hover,.action-link:focus-visible{color:var(--bright);text-decoration-color:currentColor}.action-link:focus-visible{outline:2px solid var(--info);outline-offset:3px}.action-id{direction:ltr;unicode-bidi:embed;white-space:nowrap}.findings{display:grid;gap:7px}.finding{--accent:var(--info);margin:0;padding:0;border:1px solid var(--line);border-inline-start:3px solid var(--accent);background:var(--panel);overflow:visible;scroll-margin-top:6.5rem}.finding[data-status="RISK"]{--accent:var(--risk)}.finding[data-status="PASS"]{--accent:var(--pass)}.finding[data-status="UNKNOWN"]{--accent:var(--unknown)}.finding[data-na="true"]{opacity:.68}.finding-head{display:grid;grid-template-columns:88px 1fr auto;gap:10px;align-items:start;padding:9px 10px;border-bottom:1px solid #363832}.pill{padding:2px 5px;border:1px solid currentColor;color:var(--accent);background:transparent;text-align:center;font:700 12px/17px var(--font)}.finding h2{margin:0;color:var(--bright);font:700 15px/1.3 var(--font);letter-spacing:0}.finding-meta{margin-top:3px;direction:ltr;unicode-bidi:embed}.severity{color:var(--risk);font-size:12px;font-weight:700;text-transform:uppercase}.finding-body{padding:9px 10px 10px}.explain{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:0}.explain p,.error,.evidence{margin:0;padding:5px 8px;border:0;border-inline-start:2px solid var(--line);background:var(--panel2)}.explain b{display:block;margin-bottom:4px;color:var(--muted);font-size:12px;text-transform:uppercase}details{margin-top:9px;padding-top:7px;border-top:1px solid #363832}summary{cursor:pointer;color:var(--bright);font:700 12px/1.4 var(--font)}.evidence-list{display:grid;gap:3px;margin-top:7px}.evidence{direction:ltr;text-align:left;font:12px/1.48 var(--font);overflow-wrap:anywhere}.source{color:var(--muted)}.error{color:var(--risk)}.empty{display:none;padding:38px 10px;color:var(--muted);text-align:center}.footer{margin-top:24px;padding:8px;border-top:1px solid var(--line);color:var(--muted);background:var(--panel);font-size:12px;text-align:center}
@media(max-width:720px){main{padding:28px 9px 40px}.host-grid,.summary{grid-template-columns:1fr 1fr}.host-item:nth-child(2),.summary .card:nth-child(2){border-inline-end:0}.host-item:nth-child(-n+2),.summary .card:nth-child(-n+2){border-bottom:1px solid #363832}.finding-head{grid-template-columns:76px 1fr;gap:7px}.severity{grid-column:2}.hero h1{font-size:23px}.assessment-line{grid-template-columns:1fr auto}.assessment-line span:last-child{grid-column:1/-1}.explain{grid-template-columns:1fr}.search{width:100%;min-width:0}}
@media print{:root{color-scheme:light;--bg:#fff;--panel:#fff;--panel2:#fff;--line:#555;--text:#111;--bright:#000;--muted:#555}body::before,.toolbar{display:none}main{max-width:none;padding:0}.hero::before{color:#444}.action-link{color:inherit;text-decoration:none}.finding{scroll-margin-top:0}.finding,section.card,.host-grid,.summary{break-inside:avoid}details:not([open])>*:not(summary){display:block}.footer{margin-top:15px}}
</style></head><body><main>
<header class="hero"><div><div class="eyebrow">{{t "代理 VPS 安全审计" "Proxy VPS security audit"}}</div><h1>VPS Scope</h1><div class="subtitle">{{t "自建代理、隧道和隐私网络 VPS 的安全与运行状态报告" "Security and runtime report for self-hosted proxy, tunnel, and privacy-network VPS hosts"}}</div></div></header>
<section class="host-grid" aria-label="{{t "主机信息" "Host context"}}"><div class="host-item"><span>{{t "主机" "Host"}}</span><strong>{{.Report.Host.Hostname}}</strong></div><div class="host-item"><span>{{t "系统" "System"}}</span><strong>{{.Report.Host.OS}} {{.Report.Host.OSVersion}}</strong></div><div class="host-item"><span>Profile</span><strong>{{.Report.Profile.Effective}}</strong></div><div class="host-item"><span>{{t "完成时间" "Finished"}}</span><strong>{{.Report.FinishedAt.Format "2006-01-02 15:04 UTC"}}</strong></div></section>
<section class="summary" aria-label="{{t "摘要" "Summary"}}"><div class="card risk"><div class="label">RISK</div><div class="number">{{.Report.Summary.Risk}}</div></div><div class="card pass"><div class="label">PASS</div><div class="number">{{.Report.Summary.Pass}}</div></div><div class="card info"><div class="label">INFO</div><div class="number">{{.Report.Summary.Info}}</div></div><div class="card unknown"><div class="label">UNKNOWN</div><div class="number">{{.Report.Summary.Unknown}}</div></div></section>
{{if .TimedOut}}<section class="card unknown"><h2>UNKNOWN</h2><p>{{t "审计已达到截止时间。本报告保留了已完成的证据；未运行的检查标记为 UNKNOWN。" "Audit deadline reached. This report preserves completed evidence; checks that did not run are UNKNOWN."}}</p></section>{{end}}
{{if .Assessment.HasContent}}<section class="card"><h2>{{t "代理 VPS 结论" "Proxy VPS assessment"}}</h2>{{if .Assessment.Components}}<p><b>{{t "识别到" "Detected"}}:</b> {{range $index, $component := .Assessment.Components}}{{if $index}}, {{end}}{{$component}}{{end}}</p>{{end}}<div class="assessment">{{range .Assessment.Lines}}<div class="assessment-line" data-status="{{.Status}}"><strong>{{.Label}}</strong><span class="assessment-status">{{.Status}}</span><span>{{.Message}}</span></div>{{end}}</div></section>{{end}}
<section class="card"><h2>{{.Verdict.Headline}}</h2><p>{{.Verdict.Detail}}</p><p class="muted">PASS = {{t "证据支持当前判断" "evidence supports the current judgment"}} · INFO = {{t "事实与上下文" "facts and context"}} · UNKNOWN = {{t "证据不足，不代表安全" "insufficient evidence, not safe by default"}}</p></section>
{{if or .Actions.Urgent .Actions.Availability .Actions.Maintenance .Actions.EvidenceGaps}}<section class="card"><h2>{{t "处理摘要" "Action summary"}}</h2>{{if .Actions.Urgent}}<h3>{{t "现在优先处理" "Handle now"}}</h3><ul>{{range .Actions.Urgent}}<li><a class="action-link" href="#{{anchor .Localized.ID}}"><strong>{{.Localized.Title}}</strong> <span class="action-id">({{.Localized.ID}})</span></a> — {{.Verdict}}</li>{{end}}</ul>{{end}}{{if .Actions.Availability}}<h3>{{t "可能影响可用性" "May affect availability"}}</h3><ul>{{range .Actions.Availability}}<li><a class="action-link" href="#{{anchor .Localized.ID}}"><strong>{{.Localized.Title}}</strong> <span class="action-id">({{.Localized.ID}})</span></a> — {{.Verdict}}</li>{{end}}</ul>{{end}}{{if .Actions.Maintenance}}<h3>{{t "例行维护与复核" "Maintenance and review"}}</h3><ul>{{range .Actions.Maintenance}}<li><a class="action-link" href="#{{anchor .Localized.ID}}"><strong>{{.Localized.Title}}</strong> <span class="action-id">({{.Localized.ID}})</span></a> — {{.Verdict}}</li>{{end}}</ul>{{end}}{{if .Actions.EvidenceGaps}}<h3>{{t "证据不足，需要人工确认" "Evidence gaps requiring confirmation"}}</h3><ul>{{range .Actions.EvidenceGaps}}<li><a class="action-link" href="#{{anchor .Localized.ID}}"><strong>{{.Localized.Title}}</strong> <span class="action-id">({{.Localized.ID}})</span></a> — {{.Verdict}}</li>{{end}}</ul>{{end}}</section>{{end}}
{{if .ProxyOverview.HasContent}}<section class="card"><h2>{{t "代理部署明细" "Proxy deployment details"}}</h2>{{if .ProxyOverview.Components}}<p><b>{{t "已识别组件" "Detected components"}}:</b> {{range $index, $component := .ProxyOverview.Components}}{{if $index}}, {{end}}{{$component}}{{end}}</p>{{end}}{{range .ProxyOverview.Groups}}<h3>{{.Title}}</h3><ul>{{range .Lines}}<li>{{.}}</li>{{end}}</ul>{{end}}</section>{{end}}
<section><h2>{{t "全部技术检查与证据" "All technical checks and evidence"}}</h2><p class="muted">{{t "以下是审计底稿；普通使用者通常只需阅读上面的结论和处理摘要。" "This is the audit record; most users only need the assessment and action summary above."}}</p></section>
<div class="toolbar"><div class="filters" role="group" aria-label="{{t "状态筛选" "Status filters"}}"><button class="filter" data-filter="ALL" aria-pressed="true">{{t "全部" "All"}}</button><button class="filter" data-filter="RISK" aria-pressed="false">RISK</button><button class="filter" data-filter="UNKNOWN" aria-pressed="false">UNKNOWN</button><button class="filter" data-filter="PASS" aria-pressed="false">PASS</button><button class="filter" data-filter="INFO" aria-pressed="false">INFO</button></div><input class="search" type="search" placeholder="{{t "搜索检查、证据或 ID" "Search checks, evidence, or IDs"}}" aria-label="{{t "搜索报告" "Search report"}}"></div>
<section class="findings" aria-label="{{t "检查结果" "Findings"}}">{{range .Findings}}<article class="finding" id="{{anchor .ID}}" data-status="{{.Status}}" data-na="{{.NotApplicable}}"><header class="finding-head"><div class="pill">{{.Status}}</div><div><h2>{{.Title}}</h2><div class="finding-meta">{{.ID}} · {{cat .Category}}{{if .ReasonCode}} · {{.ReasonCode}}{{end}}{{if .NotApplicable}} · {{t "不适用" "Not applicable"}}{{end}}</div></div>{{if .Severity}}<div class="severity">{{.Severity}}</div>{{end}}</header><div class="finding-body">{{if .Error}}<p class="error">{{.Error}}</p>{{end}}{{if or (eq .Status "RISK") (eq .Status "UNKNOWN")}}<div class="explain"><p><b>{{t "风险解释" "Why it matters"}}</b>{{.Why}}</p><p><b>{{t "建议" "Suggestion"}}</b>{{.Recommendation}}</p></div>{{end}}{{if .Evidence}}<details {{if or (eq .Status "RISK") (eq .Status "UNKNOWN")}}open{{end}}><summary>{{t "证据" "Evidence"}} · {{len .Evidence}}</summary><div class="evidence-list">{{range .Evidence}}<div class="evidence"><span class="source">[{{.Source}}]</span> {{evidence .}}</div>{{end}}</div></details>{{end}}</div></article>{{end}}</section>
<div class="empty">{{t "没有符合当前筛选条件的结果。" "No findings match the current filters."}}</div><footer class="footer">VPS Scope {{.Report.ToolVersion}} · schema {{.Report.SchemaVersion}} · {{t "报告保存在本地" "Report remains local"}}</footer>
</main><script>
(()=>{const buttons=[...document.querySelectorAll('[data-filter]')],items=[...document.querySelectorAll('.finding')],input=document.querySelector('.search'),empty=document.querySelector('.empty');let filter='ALL';const apply=()=>{const q=input.value.trim().toLowerCase();let shown=0;for(const item of items){const visible=(filter==='ALL'||item.dataset.status===filter)&&(!q||item.textContent.toLowerCase().includes(q));item.hidden=!visible;if(visible)shown++}empty.style.display=shown?'none':'block'};for(const button of buttons)button.addEventListener('click',()=>{filter=button.dataset.filter;for(const other of buttons)other.setAttribute('aria-pressed',String(other===button));apply()});input.addEventListener('input',apply)})();
</script></body></html>`
